Commerce.Employee = DS.Model.extend
  title: DS.attr('string')
  firstName: DS.attr('string')
  lastName: DS.attr('string')
  dateOfBirth: DS.attr('string')
  niNumber: DS.attr('string')
  address1: DS.attr('string')
  address2: DS.attr('string')
  town: DS.attr('string')
  postcode: DS.attr('string')
  mobilePhone: DS.attr('string')
  homePhone: DS.attr('string')
  startDate: DS.attr('date')
  endDate: DS.attr('date')
